
name: Digitarium
description: Understanding how things work. One little piece at a time.
url: https://www.digitarium.tk/
baseurl: 

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar:

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon:


# 菜单中的按钮
navigation:
  - name: Home page
    url: /
  - name: Tags
    url: /tags

# 每页的文章数
paginate: 4

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links:
  # weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: peterbryz@yahoo.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: pyotr777 #https://github.com/<>
  instagram: pyotr777 #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: # pyotr777 #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  youtube: pyotr777 # channel/<your_long_string> or user/<user-name>
  twitter: pyotr777 # https://www.twitter.com/<your_twitter_username>


# 站点页脚的文字
footer-text: Copyright (c) 2019-2021 Bryzgalov Peter, <a href="https://stair.center" target="_blank">Stair lab</a>, <a href="http://www.it-chiba.ac.jp" target="_blank">Chiba Institute of Technology</a>, Japan

# 输入Disqus shortname，即可添加评论区，细节可阅读文档。
# disqus: loffer #shortname

# 输入Google Analytics web tracking code
#google_analytics:

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
# url:

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
# baseurl: ""


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins_dir:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# excerpt_separator: ---
